# Generated by Django 5.0.7 on 2024-11-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_school_style_chatmessage_review_school_styles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='styles',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Style',
        ),
    ]
